### ISSUE TITLE
trying to load icomoon icon set...

### ISSUE THREAD

**Issue by sunnee5150** [keremciu/font-bundles#11]
heres my process...

![screen shot 2016-11-30 at 5 44 21 pm](https://cloud.githubusercontent.com/assets/6743214/20774528/b7909888-b724-11e6-86f7-eb7b5135c5d6.png)

![screen shot 2016-11-30 at 5 45 46 pm](https://cloud.githubusercontent.com/assets/6743214/20774558/e0de9db6-b724-11e6-9fb4-5b52494daf61.png)

after opening that folder, the font bundle does not show up, even after a restart.  I also tried to install the individual svg and ttf, neither worked.  Please help!

**Comment by keremciu** [comment]
hello @sunnee5150 

Can you try "Install a Font [SVG]" command? select only svg file of iconfont

**Comment by sunnee5150** [comment]
ok, that brings up this window -what does this mean?  How do I proceed?

![screen shot 2016-12-01 at 10 47 09 am](https://cloud.githubusercontent.com/assets/6743214/20800472/9d43d6a4-b7b3-11e6-8507-2fabeaa2645a.png)

**Comment by keremciu** [comment]
you need to click "+ import this font"  only

**Comment by edge0703** [comment]
Same here: I add a few icons in IcoMoon, download the SVG, open it in your plugin, also install the TTF file, but all I get when I go to "Icon Font > Grid Insert > icomoon" is this screen: 
![image](https://cloud.githubusercontent.com/assets/2077473/21284469/21e75b82-c41c-11e6-9665-a8a0c0aefc17.png)

How can I make the individual fonts show up?

**Comment by keremciu** [comment]
@edge0703 hello, I will try to take a video tonight, I hope it will be best direction about how can use another fonts

**Comment by edge0703** [comment]
That would be great, really looking forward to it. I want to use your plugin as a reference in a recent article I write for net magazine.

**Comment by keremciu** [comment]
@edge0703 I took the video, I'm trying to edit that I hope it will released soon

**Comment by keremciu** [comment]
@edge0703 guys I will share it without video edits on Youtube, this will be all about how can you do that when I publish the edited version, I'd like to help to share it :)

**Comment by edge0703** [comment]
That's okay for me. I think I can life fine with the unedited version. :)

**Comment by keremciu** [comment]
@sunnee5150 http://recordit.co/wy5ihqjPml you can learn how you can add a custom icon font
