### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by huyphan2602** [keremciu/font-bundles#12]
I don't know why my plugin doesn't work anymore. Nothing happens in the whole plugin when I click on any tabs (grid insert, all insert,...). 

I tried to reinstall the plugin again but it doesn't change.

**Comment by huyphan2602** [comment]
It used to work before

**Comment by huyphan2602** [comment]
My problem is here.

https://youtu.be/G1WWHSEVig4

**Comment by elecricaal** [comment]
I am having the same issue here! any solution for it?

**Comment by huyphan2602** [comment]
@elecricaal I already solved the problem, I think the reason is struggling with another plugin and after uninstalling Auto Layout plugin, It works again for me.

**Comment by elecricaal** [comment]
Thanks @huyphan2602 it worked! but does it mean i won't be able to use Auto Layout plugin again?

**Comment by huyphan2602** [comment]
@elecricaal I don't know but I think we have to choose 1 at the moment. Hope the devs can solve it as soon as possible.

**Comment by keremciu** [comment]
@huyphan2602 @elecricaal are you using Sketch Autolayout? then you should update it https://twitter.com/keremciu/status/816927771226230784

**Comment by keremciu** [comment]
it is not related with my plugin and anima app had released a new version about this problem guys
