### ISSUE TITLE
Where to find font-bundles-master?

### ISSUE THREAD

**Issue by jlong** [keremciu/font-bundles#15]
Where can I find the `font-bundles-master` folder mentioned in the readme?

**Comment by odajay** [comment]
For that, you will have to click on the "Clone or Download" button.
![screenshot 2017-04-10 17 06 42](https://cloud.githubusercontent.com/assets/3115392/24868370/17db451a-1e10-11e7-8b7f-d2eeb7016845.png)
It will download a file called font-bundles-master.zip
![screenshot 2017-04-10 17 07 29](https://cloud.githubusercontent.com/assets/3115392/24868412/3fd5fc40-1e10-11e7-8f21-ea7d473ea8aa.png)

**Comment by keremciu** [comment]
@odajay thank you @jlong I hope you find that?
