### ISSUE TITLE
I can't choose the files to install font-bundle

### ISSUE THREAD

**Issue by Peirui0505** [keremciu/font-bundles#16]
Today I upgrade sketch to V43.1. All the plugins are lost. Then I start to install them again.
After I install the ttf-files, I can't select the files to install font-bundle.
<img width="667" alt="wx20170410-234330 2x" src="https://cloud.githubusercontent.com/assets/27223948/24870059/b0a4cd3e-1e47-11e7-9ab4-bd2c87b62736.png">
<img width="390" alt="wx20170410-234309 2x" src="https://cloud.githubusercontent.com/assets/27223948/24870060/b0cc2c8a-1e47-11e7-9b7c-84beba029a7e.png">

**Comment by keremciu** [comment]
you should choose the parent folder of bundle folder, you can watch video for that
