### ISSUE TITLE
Font bundle doesn't work

### ISSUE THREAD

**Issue by sureshmurali** [keremciu/font-bundles#18]
OS version : macOS Sierra 10.12.4
Sketch version : 43.2
IconFont plugin version : 4.5.1

Found Chinese characters and Question marks instead of icons

<img width="638" alt="screen shot 2017-05-01 at 10 06 03" src="https://cloud.githubusercontent.com/assets/8108361/25569649/26bb5cfe-2e56-11e7-9158-4fc31021f645.png">

**Comment by slemouillour** [comment]
same bug for me

**Comment by slemouillour** [comment]
You need to install otf file
