### ISSUE TITLE
Old version of fontawesome

### ISSUE THREAD

**Issue by chadlavi** [keremciu/font-bundles#19]
Several fontawesome icons are missing from the included bundle (for example, `fa-user-o`). Believe this indicates that you've got an older version of the fontawesome font included in your bundle.

**Comment by chadlavi** [comment]
cf http://fontawesome.io/icon/user-o/

this actually looks like a problem with your json—the fontawesome ttf you include here has the new icons, but you're not bundling them

**Comment by keremciu** [comment]
@chadlavi oh okay I will update the font file ✌🏻
