### ISSUE TITLE
latest version doesn't work

### ISSUE THREAD

**Issue by bzx** [keremciu/font-bundles#23]
I had FA font installed previously, now the plugin doesn't recognize the font, and I can't use the plugin.

**Comment by rymorgan** [comment]
I'm experiencing the same thing. A fix would be awesome b/c I love this plugin. So helpful!

**Comment by joedaniels** [comment]
+1 having the same proble.

Used to work fine for me, now none of the icon fonts work at all.

**Comment by keremciu** [comment]
@bzx @joedaniels Are you using high sierra? I tried to reproduce your case but can't

**Comment by bzx** [comment]
@keremciu I'm on Sierra.

**Comment by joedaniels** [comment]
@keremciu yes I am

**Comment by achiandet** [comment]
This solution resolved the problem for me.  https://github.com/keremciu/font-bundles/issues/25

FWIW: High Sierra, Sketch 48

**Comment by joedaniels** [comment]
Randomly started working again for me

**Comment by keremciu** [comment]
@joedaniels @achiandet @bzx 

sorry guys, I couldn't reproduce it, I hope you're enjoying the plugin! I'm working on a new version which has a nice font install solution
