### ISSUE TITLE
How to use FontAwesome 5

### ISSUE THREAD

**Issue by Animalejourbano** [keremciu/font-bundles#25]
I can't make the new font awesome 5 works. Are you going to update this bundle?

**Comment by keremciu** [comment]
@Animalejourbano oh yes I will try to update font awesome 5

**Comment by laughnan** [comment]
i'm interested in this as well.

**Comment by keremciu** [comment]
@laughnan @Animalejourbano 

http://recordit.co/PpAU3IVcNT

I made a video about that. You can learn that how you can use font awesome 5 with plugin.

I'll add them into font-bundles with more clear version, soon.

**Comment by Animalejourbano** [comment]
Thanks a lot!!!

**Comment by temology** [comment]
OMG! Thank you for this, worked like magic!

**Comment by byezgi-esq** [comment]
Goodbye my favorite plugin! Doesn't work with the Fontawesome Pro version :( I have looked at all the related threads linked from here and still no luck.

**Comment by temology** [comment]
> Goodbye my favorite plugin! Doesn't work with the Fontawesome Pro version :( I have looked at all the related threads linked from here and still no luck.

@byezgi-esq Did you change the name of the font in .svg file?
This is what I did. Opened .svg font file in code editor and renamed the each font

**Comment by byezgi-esq** [comment]
> @byezgi-esq Did you change the name of the font in .svg file?
> This is what I did. Opened .svg font file in code editor and renamed the each font

Yes I made sure the font-family and font-id are the same etc. I do see the font in sketch but when I click on it and view the icons in it (using the plugin) it only shows me a handful OK icons and a bunch of broken thumbnails. I double checked the ttf file of the font, no problems. Ended up just using the font directly by copying the glyphs into text.

**Comment by keremciu** [comment]
@byezgi-esq I can try to help you about the case, is it okay for you to watch my steps from a screen video? or you can try to explain your steps by text then I will understand which step has a problem

**Comment by cairnchampagne** [comment]
I only get a few icons - not the whole set:
![Screen Shot 2019-03-21 at 10 29 50 AM](https://user-images.githubusercontent.com/25507541/54759352-497b4780-4bc4-11e9-81ae-327d1b0ad430.png)

**Comment by byezgi-esq** [comment]
@cairnchampagne I see the same screen using Pro. I followed the directions in this thread, no luck.

**Comment by keremciu** [comment]
@byezgi-esq @cairnchampagne 

We're talking about this issue in this thread: https://github.com/keremciu/sketch-iconfont/issues/170

**Comment by anthonycmain** [comment]
Doesnt seem to work with v5.9 for some reason, only get a few icons to select from any ideas?
