### ISSUE TITLE
installing bundles

### ISSUE THREAD

**Issue by mrhargro** [keremciu/font-bundles#26]
i have used your plugin a lot, but got a new machine and i'm trying to install the bundles.  for whatever reason double clicking the font bundle doesn't bring me to install window. any tips?
![bundle install](https://user-images.githubusercontent.com/2421704/34008849-af247f2c-e0d4-11e7-842b-ce5da9f4e4a0.gif)

**Comment by mrhargro** [comment]
hmmm. i just re-downloaded them and it seems to work!

**Comment by keremciu** [comment]
@mrhargro working on a new update about installation process, I hope it will fix these problems
