### ISSUE TITLE
Use these Font Awesome 5 working names :)

### ISSUE THREAD

**Issue by sogen** [keremciu/font-bundles#30]
Just in case anyone needs the right names for the SVG install to work:

Font Awesome 5 Free
Font Awesome 5 Free Solid
Font Awesome 5 Brands

Just make sure the SVG `font id` and `font-face font-family` have these names
😄

**Comment by keremciu** [comment]
yep I made a video about it, I talked with them about pro fonts, I will publish a new version for the plugin

https://github.com/keremciu/font-bundles/issues/25

**Comment by Animalejourbano** [comment]
It works also for pro fonts. I've used the following names and they work grate! Thanks a lot @keremciu for your work: 
Font Awesome 5 Pro Light
Font Awesome 5 Pro
Font Awesome 5 Pro Solid

**Comment by keremciu** [comment]
@Animalejourbano oh so nice man! you know the problem font-ids and font-family names are different, can you give me a list font-ids and font-families for pro fonts?

I will just add them here:
https://github.com/keremciu/sketch-iconfont/blob/master/iconfont.sketchplugin/Contents/Sketch/const/import.js#L17

then when a user add that font, there will not be a problem, if you'd like to contribute you can send a PR about it!

**Comment by Animalejourbano** [comment]
There is a problem with that, because all pro fonts have the same id, which is "fontawesome-pro" . At least in the version 5.0.4
The difference between each font it's given by the "font-face" and "font-weight" attributes of the "font-face" element. 

`<font-face font-family="Font Awesome 5 Pro" font-weight="300" font-style="Light" />
<font-face font-family="Font Awesome 5 Pro" font-weight="400" font-style="Regular" />
<font-face font-family="Font Awesome 5 Pro" font-weight="900" font-style="Solid" />`

**Comment by steveharman** [comment]
We just upgraded to FA Pro (5.0.6) but I'm hugely confused how to get FA Pro 5.0.6 working with the Icon Font plugin.  Is there a step-by-step guide?   Thanks,

**Comment by frankydev** [comment]
I'm using:
`  <font id="Font Awesome 5 Brands" horiz-adv-x="640.4">
    <font-face font-family="Font Awesome 5 Brands"`
And it's working like a charm. 😎

**Comment by cairnchampagne** [comment]
I'm also experiencing this problem with the PRO version:
![Screen Shot 2019-03-21 at 10 29 50 AM](https://user-images.githubusercontent.com/25507541/54824342-0af79280-4c81-11e9-917d-1beec4f3ea15.png)

Just going to move over to this discussion. Hopefully, we can get this solved.

**Comment by keremciu** [comment]
@cairnchampagne did you look at your font glyphs at font book app?

**Comment by cairnchampagne** [comment]
@keremciu 

First off - great plugin. I wish icon fonts were WAY easier to use in SKETCH but, for now, it is what it is.

I don't use font book. I use Font Explorer Pro. But, all the glyphs are there:
![Screen Shot 2019-03-25 at 9 20 37 AM](https://user-images.githubusercontent.com/25507541/54922847-68891a80-4edf-11e9-9b55-b0bc06cd3d58.png)

I did the renaming trick through Visual Composer but, I don't get the full array of icons.

**Comment by keremciu** [comment]
@cairnchampagne oh, I think it's all about icon names differences between ttf file and svg file, I will try to learn how we can fix this one
