### ISSUE TITLE
Getting an error while installing the font

### ISSUE THREAD

**Issue by asaadmahmood** [keremciu/font-bundles#43]
The error that I get is:
`MOJavaScriptException: TypeError: null is not an object (evaluating 'folder_bundle. count')`

**Comment by keremciu** [comment]
@asaadmahmood were you trying one font to install or bundle?

**Comment by asaadmahmood** [comment]
@keremciu Tried both.. Didn't work.

**Comment by keremciu** [comment]
oh are you sure about you're choosing the parent folder? if you download it, it's like 'font-bundles-master'

**Comment by asaadmahmood** [comment]
@keremciu Sorry, I was doing exactly that.

**Comment by asaadmahmood** [comment]
Works like a charm now.

**Comment by keremciu** [comment]
@asaadmahmood happy to hear about that 🕺🏻 time to rock it!
