### ISSUE TITLE
Fontawesome 4.6 is out!

### ISSUE THREAD

**Issue by TrevorColeman** [keremciu/font-bundles#5]
Love the plugin! 

Just thought I'd let you know that 4.6 is out. :)

**Comment by keremciu** [comment]
yep, I will update it soon :)

**Comment by TrevorColeman** [comment]
Awesome! Thanks for making this, it saves me SO much time.

**Comment by Aminta** [comment]
Hi!

Any plan to support the Icomoon packs in your stunning plugin (https://icomoon.io/#icons-icomoon, I’ve got the Ulti)?




Thanks!

-- 
dr. Davide Lorigliola


Da: TrevorColeman <notifications@github.com>
Rispondi: keremciu/font-bundles <reply@reply.github.com>
Data: 7 giugno 2016 at 17:10:20
A: keremciu/font-bundles <font-bundles@noreply.github.com>
Oggetto:  Re: [keremciu/font-bundles] Fontawesome 4.6 is out! (#5)  

Awesome! Thanks for making this, it saves me SO much time.

**Comment by keremciu** [comment]
@TrevorColeman I've updated font-awesome to 4.6.3 you can grab it now with reinstall and I'm really happy to hear that, I hope I can make better version soon :)

**Comment by bohn002** [comment]
@keremciu doh, was just about to post my PR, beat me to it!

**Comment by keremciu** [comment]
ups sorry @bohn002 next update I will wait for you 👍 I'm so glad for chasing

**Comment by keremciu** [comment]
hello @Aminta I think I can explain that with a screen-capture video. When I have a time, I will take a video to tell how you can use icomoon

**Comment by Aminta** [comment]
Thanks!  

I've tried, but they provide a json with very different format...

--  
dr. Davide Lorigliola  


Via Colloredo 7/A
33037 Pasian di Prato (Udine)
mobile +39 329 - 618 618 9(tel:+39%20329%20-%20618%20618%209)  
davide.lorigliola@icloud.com(mailto:davide.lorigliola@icloud.com)
www.360vr.it(http://www.360vr.it/)



Il giorno 7 giugno 2016 @ 22:15:05, Kerem Sevencan (notifications@github.com(mailto:notifications@github.com)) ha scritto:
