### ISSUE TITLE
Issue with the plugin

### ISSUE THREAD

**Issue by kiosria** [keremciu/font-bundles#8]
Hi, I would love to use your amazing tool. But, I can't seem to make it work. I think, I tried everything before coming here. I got the plugin installed, installed the fonts, it's on the OS. And I linked it to the bundle master... But still nothing and there is this empty square... Thanks a lot ! 
<img width="1440" alt="capture d ecran 2016-10-21 a 11 12 48" src="https://cloud.githubusercontent.com/assets/22978152/19593344/81a1b2f2-9780-11e6-8ec3-e417670e411a.png">
<img width="1440" alt="capture d ecran 2016-10-21 a 11 13 10" src="https://cloud.githubusercontent.com/assets/22978152/19593355/8c8723fa-9780-11e6-87a4-bb45dc451471.png">
<img width="1440" alt="capture d ecran 2016-10-21 a 11 13 28" src="https://cloud.githubusercontent.com/assets/22978152/19593373/982b7b2a-9780-11e6-8401-dff4ceab5e9e.png">
<img width="1440" alt="capture d ecran 2016-10-21 a 11 12 38" src="https://cloud.githubusercontent.com/assets/22978152/19593384/9febbbcc-9780-11e6-9675-ab41c9677ab9.png">

**Comment by keremciu** [comment]
@kiosria hello, did you watch this video? http://recordit.co/2PMTB04Jav

**Comment by kiosria** [comment]
yeah, But I think my main issue if from the font. I doesn't show like yours ( have to go the the glyphs to see the icons ), but I don't know how to change that. I mean it's installed (screen shot), even sketch recognize it.

**Comment by keremciu** [comment]
mm I think you installed the font right, you should need to install Font-Bundle directory correctly.

Select "Install a Font-Bundle" command then select the folder which you download from this repo, it is enough to see your fonts on plugin commands.

**Comment by kiosria** [comment]
Well, I tried, but the plugin doesn't acknowledge it. I tried earlier with a svg ( from font awesome ) but it didn't show either. 
<img width="950" alt="capture d ecran 2016-10-21 a 12 45 46" src="https://cloud.githubusercontent.com/assets/22978152/19595921/64220338-978c-11e6-8102-a08fc80797fa.png">

**Comment by keremciu** [comment]
I've tried with 3.8.3 version of sketch, it is working so nice. I can't understand the problem now 😞  you select "Install a Font-Bundle" command then select "font-bundles-master" directory? and it is not working, mmm :/ 

can you send me a screencast? you can use recordit or quicktime app for that because your case is not

**Comment by kiosria** [comment]
![try](https://cloud.githubusercontent.com/assets/22978152/19600997/aeadcd18-97a7-11e6-82de-2d3111d6d9af.gif)

maybe it's because i'm on 3.3

**Comment by kiosria** [comment]
My file was too heavy, but maybe it's because I'm on 3.3.3 version of sketch.

**Comment by keremciu** [comment]
:/ mm, it could be a problem. can you open your console.app on macos and try to install font-bundle and then your console will tell you whats wrong with Sketch

**Comment by kiosria** [comment]
here, sorry I may have backed too much in the console [http://recordit.co/XFGk2emtgX](url)

**Comment by kiosria** [comment]
here, sorry I may have back too much in the console [http://recordit.co/XFGk2emtgX](url)

**Comment by keremciu** [comment]
@kiosria http://recordit.co/wy5ihqjPml
