### ISSUE TITLE
my icon is download iconfont，how can i put the icon in the bundle 

### ISSUE THREAD

**Issue by snowalfra** [keremciu/font-bundles#9]
my icon is download iconfont，how can i put the icon in the bundle , i don,t know how to creat fonts.json  ?

**Comment by snowalfra** [comment]
[
<img width="643" alt="2016-11-02 11 23 22" src="https://cloud.githubusercontent.com/assets/19890798/19915966/df28dcd8-a0f0-11e6-80c3-83d5860aabe8.png">
<img width="424" alt="2016-11-02 11 37 36" src="https://cloud.githubusercontent.com/assets/19890798/19915967/df5573f6-a0f0-11e6-9d06-262967dbfb64.png">
<img width="643" alt="2016-11-02 11 37 45" src="https://cloud.githubusercontent.com/assets/19890798/19915969/df757d5e-a0f0-11e6-956f-11f84cc78ae7.png">
<img width="642" alt="2016-11-02 11 37 48" src="https://cloud.githubusercontent.com/assets/19890798/19915968/df74daa2-a0f0-11e6-8fb6-06cfc2789e3b.png">



](url)

**Comment by keremciu** [comment]
hello @snowalfra 

which icon font generator do you use? you can install that iconfont with its SVG file and you can export your all bundle from plugin

**Comment by snowalfra** [comment]
http://www.iconfont.cn/plus  ，I use this website to generate  font，but i don't know how to put in the font-bundles-master ,because ,i  am  lose the fonts.json ,i don,t know how to generate

**Comment by snowalfra** [comment]
how to  install that iconfont with its SVG file ?  not work

**Comment by keremciu** [comment]
@snowalfra yep, you can install with its SVG file with "Install a Font [SVG]" command, I'm using fontello to install font to the plugin and you should only install ttf file to your osx

Bundle can be generated only by the plugin, you can't generate it manually

If you've time for this, I can do a quick video about this at weekend

**Comment by snowalfra** [comment]
but i am failed ,because the icon show chinese ,not a icon ,why ???   thank you ,i am waiting for you [
<img width="612" alt="2016-11-02 16 06 43" src="https://cloud.githubusercontent.com/assets/19890798/19920955/98ffc228-a116-11e6-8e1f-24f7be84ca83.png">
[font_lkgfe23woyge3ik9.zip](https://github.com/keremciu/font-bundles/files/565952/font_lkgfe23woyge3ik9.zip)

](url)

**Comment by keremciu** [comment]
can you use fontello.com? but I will try to handle iconfont.cn/plus service in the future

**Comment by snowalfra** [comment]
no ,i am a chinese ,so i like to use chinese webiste ,because   my english is not very  good ,haha

**Comment by snowalfra** [comment]
i am hoping for your video ,hahh ,thank you

**Comment by snowalfra** [comment]
where are you ?

**Comment by keremciu** [comment]
@snowalfra http://recordit.co/wy5ihqjPml

**Comment by snowalfra** [comment]
@keremciu  thank you  i will try it later

**Comment by snowalfra** [comment]
@keremciu   I have only one question ,why i choose a icon ,the board closed ,it to difficult to use,could save this question  ,let the board still in front of the sketch  don't close it automatically

**Comment by snowalfra** [comment]
@keremciu   another question ，why I make it as a symbol  ,i  can't input other name ,and change the icon ,you can see the picture 
<img width="248" alt="2017-01-19 14 51 49" src="https://cloud.githubusercontent.com/assets/19890798/22096530/134c238c-de57-11e6-8b75-aa5354252f72.png">

**Comment by keremciu** [comment]
@snowalfra yea, I will handle symbols with new version of plugin and multiple select

**Comment by keremciu** [comment]
@snowalfra is that right? you'd like to see two things: 1- multiple icon insert 2- editable symbol
I will write you about them with new version release :)

**Comment by snowalfra** [comment]
@keremciu  wow  you are amazing
